<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Proiect_SDA ~ Predicția unui Accident Vascular Cerebral ~</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/clipboard/clipboard.min.js"></script>
<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/quarto.js"></script>
<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/popper.min.js"></script>
<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/anchor.min.js"></script>
<link href="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducere" id="toc-introducere" class="nav-link active" data-scroll-target="#introducere">Introducere</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review">Literature Review</a></li>
  <li><a href="#încărcarea-datelor" id="toc-încărcarea-datelor" class="nav-link" data-scroll-target="#încărcarea-datelor">Încărcarea Datelor</a></li>
  <li><a href="#descrierea-datelor" id="toc-descrierea-datelor" class="nav-link" data-scroll-target="#descrierea-datelor">Descrierea Datelor</a></li>
  <li><a href="#analiza-exploratorie-a-datelor" id="toc-analiza-exploratorie-a-datelor" class="nav-link" data-scroll-target="#analiza-exploratorie-a-datelor">Analiza Exploratorie a Datelor</a></li>
  <li><a href="#regresie-logistică" id="toc-regresie-logistică" class="nav-link" data-scroll-target="#regresie-logistică">Regresie Logistică</a></li>
  <li><a href="#arbori-de-clasificare" id="toc-arbori-de-clasificare" class="nav-link" data-scroll-target="#arbori-de-clasificare">Arbori de Clasificare</a></li>
  <li><a href="#concluzii" id="toc-concluzii" class="nav-link" data-scroll-target="#concluzii">Concluzii</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proiect_SDA ~ Predicția unui Accident Vascular Cerebral ~</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducere" class="level2">
<h2 class="anchored" data-anchor-id="introducere">Introducere</h2>
<p>Prin analiza curentă ne propunem să prezicem apariția unui accident vascular cerebral în rândul unor pacienți, având în vedere informații relevante despre aceștia, care pot fi sintetizate în variabile precum: genul, vârsta, diferite boli, indicele de masă corporală, mediul de proveniență, starea civilă, starea profesională, frecventarea fumatului. Din punctul de vedere al metodologiei, vom utiliza mediul de programare R Studio pentru analiza exploratorie a datelor, dar și pentru aplicarea unor metode precum regresia logistică și arborii de clasificare.</p>
<p>Este bine cunoscut faptul că unul dintre cele mai complexe și importante organe ale corpului este creierul, fără de care nu ne putem desfășura activitățile de zi cu zi, întrucât acesta este responsabil de coordonarea tuturor funcțiilor vitale, a comportamentului, gândurilor și trăirilor pe care le avem.</p>
<p>De asemenea, printre cele mai frecvente cauze de deces în rândul oamenilor se numără accidentul vascular cerebral. Acesta este cunoscut frecvent sub denumirea de AVC și se produce în momentul în care alimentarea cu sânge a unei zone de creier este întreruptă sau redusă, împiedicând țesutul cerebral să primească oxigen și substanțe nutritive. Astfel, în decurs de câteva minute, celulele creierului încep să se degradeze și să se distrugă. Au fost identificate două tipuri principale de AVC:</p>
<ul>
<li>Ischemic: cauzat de blocarea fluxului de sânge dintr-un vas care este conectat cu creierul</li>
<li>Hemoragic: cauzat de sângerare excesivă la nivelul creierului</li>
</ul>
<p>Printre consecințele acestora se numără și efectele grave și de lungă durată asupra organismului pacientului, precum dificultăți de vorbire, mișcare, gândire, dar și un risc foarte ridicat de deces. Studiul AVC-ului este o problemă de importanță majoră la nivel mondial, drept pentru care Organizația Mondială a Sănătății furnizează anual informații despre numărul persoanelor decedate sau afectate de această boală (spre exemplu: aproximativ 15 milioane de persoane în anul 2020 – OMS).</p>
<p>În ceea ce ne privește, considerăm că domeniul sănătății ar trebui să fie de un mai mare interes la nivel național și internațional, deoarece sănătatea oamenilor ar trebui să primeze indiferent de circumstanțe. De asemenea, este de datoria noastră să realizăm cât mai multe cercetări în acest sector pentru a putea preveni sau chiar remedia apariția acestei boli. Inovațiile și descoperirile ar trebui să fie concentrate în identificarea unor tratamente mai eficiente și îmbunătățirea celor actuale, fiind cruciale pentru minimizarea efectelor negative ale accidentului vascular cerebral.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">Literature Review</h2>
<p>Având în vedere importanța acestei problematici la nivel mondial, au fost realizate diverse studii în ceea ce privește analiza factorilor care influențează apariția unui accident vascular cerebral, folosind metode utilizate în data science.</p>
<p>Spre exemplu, în articolul ”A predictive analytics approach for stroke prediction using machine learning and neural networks” (Soumyabrata Dev, et al., sursa: https://www.sciencedirect.com) sunt analizați sistematic diverși factori din fișele medicale electronice ale unor pacienți pentru predicția eficientă a unui AVC. Au fost utilizate tehnici statistice și analiza componentelor principale pentru a ajunge la concluzia că vârsta, bolile de inimă, nivelul mediu de glucoză și hipertensiunea arterială sunt cei mai importanți factori în acest sens. De asemenea, a fost construită și o rețea neuronală care utilizează aceste patru atribute ce oferă cea mai mare rată de acuratețe și cea mai mică rată de pierderi în comparație cu utilizarea tuturor caracteristicilor de intrare disponibile și a altor algoritmi de evaluare comparativă.</p>
<p>De asemenea, articolul intitulat ”Stroke Risk Factors, Genetics, and Prevention” (Amelia K. Boehme et al., sursa: https://www.ncbi.nlm.nih.gov/, National Library of Medicine) ne arată existența factorilor de risc ai AVC care nu pot fi modificați (ex: vârsta, genul, rasa și istoricul familial), dar și factorii de risc care pot fi modificați (ex: hipertensiunea). În general, apariția AVC este posibilă odată cu înaintarea în vârstă și cu creșterea tensiunii arteriale, stabilindu-se o legătură directă între aceste variabile și scopul urmărit. Printre soluțiile propuse de cercetători se numără schimbarea stilului de viață, a nutriției, evitarea excesului de alcool, tutun, controlul periodic la medic.</p>
<p>Un ultim exemplu este studiul “Analysis of main risk factors causing stroke in Shanxi Province based on machine learning models“ (Junjie Liu, et al., sursa: https://www.sciencedirect.com), unde a fost analizat un set de date cu pacienți ce suferă de AVC (2000) și rezidenți (27.583), aplicându-se modele de arbori de decizie, random forest și regresie logisitcă pentru a evalua probabilitatea de apariție a unui AVC pe diferite niveluri de risc. Astfel, s-a demonstrat că hipertensiunea arterială, inactivitatea fizică și excesul de greutate sunt clasați ca primii trei factori de risc ridicat de AVC în Shanxi.</p>
</section>
<section id="încărcarea-datelor" class="level2">
<h2 class="anchored" data-anchor-id="încărcarea-datelor">Încărcarea Datelor</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>stroke_pred<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'stroke_data.csv'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id gender age hypertension heart_disease ever_married     work_type
1  9046   Male  67            0             1          Yes       Private
2 51676 Female  61            0             0          Yes Self-employed
3 31112   Male  80            0             1          Yes       Private
4 60182 Female  49            0             0          Yes       Private
5  1665 Female  79            1             0          Yes Self-employed
6 56669   Male  81            0             0          Yes       Private
  Residence_type avg_glucose_level  bmi  smoking_status stroke
1          Urban            228.69 36.6 formerly smoked      1
2          Rural            202.21  N/A    never smoked      1
3          Rural            105.92 32.5    never smoked      1
4          Urban            171.23 34.4          smokes      1
5          Rural            174.12   24    never smoked      1
6          Urban            186.21   29 formerly smoked      1</code></pre>
</div>
</div>
</section>
<section id="descrierea-datelor" class="level2">
<h2 class="anchored" data-anchor-id="descrierea-datelor">Descrierea Datelor</h2>
<p>Pentru realizarea analizei curente am folosit ca sursă de date site-ul www.kaggle.com. Setul de date inițial este alcătuit din 5110 observații (pacienți) și 12 coloane (atribute). Astfel, variabilele utilizate sunt:</p>
<ul>
<li>id: identificator unic al pacientului</li>
<li>gen: “Male”, “Female” sau “Other”</li>
<li>age: vârsta pacientului</li>
<li>hypertension: valoarea 0, dacă pacientul nu suferă de hipertensiune; valoarea 1 dacă pacientul suferă de hipertensiune</li>
<li>heart_disease: valoarea 0, dacă pacientul nu suferă de boli de inimă; valoarea 1 dacă pacientul suferă de boli de inimă</li>
<li>ever_married: starea civilă – “No” (necăsătorit) sau “Yes” (căsătorit)</li>
<li>work_type: starea profesională – “children”, “Govt_jov”, “Never_worked”, “Private” sau “Self-employed”</li>
<li>Residence_type: mediul de proveniență – “Rural” sau “Urban”</li>
<li>avg_glucose_level: nivelul mediu de glucoză din sânge</li>
<li>bmi: indicele de masă corporală</li>
<li>smoking_status: frecvența fumatului – “formerly smoked”, “never smoked”, “smokes” sau “Unknown” (informația nu este disponibilă pentru pacientul respectiv)</li>
<li>stroke: valoarea 0, dacă pacientul nu a avut un AVC; valoarea 1, dacă pacientul a avut un AVC</li>
</ul>
<p><strong>Ilustrarea datelor</strong></p>
<p>Pentru o înțelegere mai clară a setului de date, am ales să codificăm în ”Yes” și ”No” valorile de 0 și 1 pentru coloanele hypertension, heart_disease și stroke.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>stroke_data <span class="ot">&lt;-</span> stroke_pred <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hypertension =</span> <span class="fu">if_else</span>(hypertension <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">heart_disease =</span> <span class="fu">if_else</span>(heart_disease <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi=</span> <span class="fu">as.double</span>(bmi),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">stroke =</span> <span class="fu">if_else</span>(stroke <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="sc">%&gt;%</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mask$eval_all_mutate(quo): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id gender age hypertension heart_disease ever_married     work_type
1  9046   Male  67           No           Yes          Yes       Private
2 51676 Female  61           No            No          Yes Self-employed
3 31112   Male  80           No           Yes          Yes       Private
4 60182 Female  49           No            No          Yes       Private
5  1665 Female  79          Yes            No          Yes Self-employed
6 56669   Male  81           No            No          Yes       Private
  Residence_type avg_glucose_level  bmi  smoking_status stroke
1          Urban            228.69 36.6 formerly smoked    Yes
2          Rural            202.21   NA    never smoked    Yes
3          Rural            105.92 32.5    never smoked    Yes
4          Urban            171.23 34.4          smokes    Yes
5          Rural            174.12 24.0    never smoked    Yes
6          Urban            186.21 29.0 formerly smoked    Yes</code></pre>
</div>
</div>
</section>
<section id="analiza-exploratorie-a-datelor" class="level2">
<h2 class="anchored" data-anchor-id="analiza-exploratorie-a-datelor">Analiza Exploratorie a Datelor</h2>
<p><strong>Statistici Descriptive</strong></p>
<p>În continuare, am ales să analizăm statisticile descriptive pentru setul nostru de date folosind funcția summary () pentru identificarea valorilor minime, maxime, a mediei, a medianei și a primei și a treia cuartile pentru variabilele numerice, dar și pentru contorizarea numărului de pacienți în funcție de segmentarea variabilelor rămase.</p>
<p>Spre exemplu, vârsta medie a pacienților analizați este de aproximativ 43 de ani, cei mai tineri dintre aceștia având vârsta de 1 an, iar cei cu vârste mai înaintate de 82 de ani. În rândul acestora, nivelul mediu de glucoză din sânge se situează între 55.12 mmol/l și 271.74 mmol/l, în timp ce indicele de masă corporală variază între 10.30 kg/m² și 97.60 kg/m², având o valoare medie de 28.89 kg/m².</p>
<p>Referitor la variabilele calitative, observăm cum predomină pacienții de genul feminin (2994), cei care lucrează în mediul privat (2925) și care sunt căsătoriți (3353), cei mai mulți fiind nefumători (1892). Distribuția urban/rural este aproximativ egală, un număr redus de persoane a înregistrat alte boli precum hipertensiune/boli de inimă și doar un număr de 249 de persoane au suferit un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stroke_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id           gender          age        hypertension heart_disease
 Min.   :   67   Female:2994   Min.   : 0.08   No :4612     No :4834     
 1st Qu.:17741   Male  :2115   1st Qu.:25.00   Yes: 498     Yes: 276     
 Median :36932   Other :   1   Median :45.00                             
 Mean   :36518                 Mean   :43.23                             
 3rd Qu.:54682                 3rd Qu.:61.00                             
 Max.   :72940                 Max.   :82.00                             
                                                                         
 ever_married         work_type    Residence_type avg_glucose_level
 No :1757     children     : 687   Rural:2514     Min.   : 55.12   
 Yes:3353     Govt_job     : 657   Urban:2596     1st Qu.: 77.25   
              Never_worked :  22                  Median : 91.89   
              Private      :2925                  Mean   :106.15   
              Self-employed: 819                  3rd Qu.:114.09   
                                                  Max.   :271.74   
                                                                   
      bmi                smoking_status stroke    
 Min.   :10.30   formerly smoked: 885   No :4861  
 1st Qu.:23.50   never smoked   :1892   Yes: 249  
 Median :28.10   smokes         : 789             
 Mean   :28.89   Unknown        :1544             
 3rd Qu.:33.10                                    
 Max.   :97.60                                    
 NA's   :201                                      </code></pre>
</div>
</div>
<p>De asemenea, am folosit și funcția describe () pentru analizarea coeficienților de asimetrie (skew) și boltire (kurtosis) pentru variabilele numerice. Astfel, variabila age înregistrează valori negative ( &lt; 0 ) ale coeficientului de variație (-0.14), ceea ce înseamnă că distribuția valorilor prezintă o ușoară asimetrie la stânga, predominând valorile mari în ceea ce privește vârsta pacienților. Variabilele referitoare la nivelul mediu de glucoză (avg_glucose_level) și la indicele de masă corporală (bmi) înregistrează valori pozitive ( &gt; 0 ) ale coeficientului de variație (1.57 &amp; 1.05), ceea ce înseamnă că distribuția acestora prezintă asimetrie la dreapta, predominând valorile mici în cadrul acestor variabile.</p>
<p>Referitor la valorile coeficientului de boltire, variabilele age (-0.99) și avg_glucose_level (1.68) au distribuții platicurtice ( &lt; 3 ), în timp ce variabila bmi (3.36) are o distribuție leptocurtică ( &gt; 3 ).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("psych")</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(stroke_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  vars    n     mean       sd   median  trimmed      mad   min
id                   1 5110 36517.83 21161.72 36932.00 36542.26 27413.27 67.00
gender*              2 5110     1.41     0.49     1.00     1.39     0.00  1.00
age                  3 5110    43.23    22.61    45.00    43.61    26.69  0.08
hypertension*        4 5110     1.10     0.30     1.00     1.00     0.00  1.00
heart_disease*       5 5110     1.05     0.23     1.00     1.00     0.00  1.00
ever_married*        6 5110     1.66     0.48     2.00     1.70     0.00  1.00
work_type*           7 5110     3.50     1.28     4.00     3.62     0.00  1.00
Residence_type*      8 5110     1.51     0.50     2.00     1.51     0.00  1.00
avg_glucose_level    9 5110   106.15    45.28    91.88    97.85    26.06 55.12
bmi                 10 4909    28.89     7.85    28.10    28.34     6.97 10.30
smoking_status*     11 5110     2.59     1.09     2.00     2.61     1.48  1.00
stroke*             12 5110     1.05     0.22     1.00     1.00     0.00  1.00
                       max    range  skew kurtosis     se
id                72940.00 72873.00 -0.02    -1.21 296.03
gender*               3.00     2.00  0.35    -1.86   0.01
age                  82.00    81.92 -0.14    -0.99   0.32
hypertension*         2.00     1.00  2.71     5.37   0.00
heart_disease*        2.00     1.00  3.94    13.57   0.00
ever_married*         2.00     1.00 -0.66    -1.57   0.01
work_type*            5.00     4.00 -0.91    -0.49   0.02
Residence_type*       2.00     1.00 -0.03    -2.00   0.01
avg_glucose_level   271.74   216.62  1.57     1.68   0.63
bmi                  97.60    87.30  1.05     3.36   0.11
smoking_status*       4.00     3.00  0.08    -1.35   0.02
stroke*               2.00     1.00  4.19    15.57   0.00</code></pre>
</div>
</div>
<p><strong>Valori lipsă</strong></p>
<p>Pentru curățarea datelor este necesară identificarea valorilor lipsă din setul de date. Astfel, doar pentru variabila bmi am identificat un număr de 201 observații lipsă, pe care le-am eliminat cu ajutorul funcție na.omit().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(stroke_data, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               id            gender               age      hypertension 
                0                 0                 0                 0 
    heart_disease      ever_married         work_type    Residence_type 
                0                 0                 0                 0 
avg_glucose_level               bmi    smoking_status            stroke 
                0               201                 0                 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>stroke_data2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(stroke_data)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#stroke_data2</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(stroke_data2, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               id            gender               age      hypertension 
                0                 0                 0                 0 
    heart_disease      ever_married         work_type    Residence_type 
                0                 0                 0                 0 
avg_glucose_level               bmi    smoking_status            stroke 
                0                 0                 0                 0 </code></pre>
</div>
</div>
<p><strong>Identificare duplicate</strong></p>
<p>De asemenea, este esențială verificarea existenței duplicatelor. Deoarece nu există duplicate, nou set de date rămâne cu un număr de 4909 observații rezultate în urma prelucrărilor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(stroke_data2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><strong>Distribuția procentuală în rândul pacienților</strong></p>
<p>Referitor la distribuția procentuală a pacienților analizați, observăm cum 96% (4700) dintre aceștia nu au suferit un AVC, în timp ce 4 % (209) au suferit un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>stroke_data2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(stroke) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">patients =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span>  <span class="fu">mutate</span>(<span class="at">total =</span> <span class="fu">sum</span>(patients), <span class="at">percent =</span> scales<span class="sc">::</span><span class="fu">percent</span>(patients<span class="sc">/</span>total))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  stroke patients total percent
  &lt;fct&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;  
1 No         4700  4909 96%    
2 Yes         209  4909 4%     </code></pre>
</div>
</div>
<p><strong>Distribuția variabilelor discrete</strong></p>
<p>Pentru o reprezentare vizuală mai clară și pentru confirmarea rezultatelor anterioare, am construit histogramele variabilelor de tip numeric. Astfel, pentru variabila age sunt predominante valorile mai mari de vârstă. Observăm o accentuată asimetrie la dreapta și predominanța valorilor mici pentru variabila avg_glucose_level. De asemenea, asimetria la dreapta și frecvența mare a valorilor mici sunt vizibile și pentru variabila bmi.</p>
<div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>H_age<span class="ot">&lt;-</span>stroke_data2<span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(age))<span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">"plum3"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col=</span><span class="st">"plum4"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>H_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>H_glucose<span class="ot">&lt;-</span>stroke_data2<span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(avg_glucose_level))<span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">"skyblue2"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col=</span><span class="st">"skyblue3"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>H_glucose</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>H_bmi<span class="ot">&lt;-</span>stroke_data2<span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(bmi))<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">"salmon2"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col=</span><span class="st">"salmon3"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>H_bmi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p><strong>Densitate avg_glucose_level – stroke</strong></p>
<p>Graficul relației dintre nivelul mediu de glucoză din sânge și apariția unui AVC arată faptul că pacienții cu un nivel mediu mai mare de 200 mmol/l au suferit un AVC, în timp ce pacienții cu un nivel mediu cuprins între 50 și 130 mmol/l nu au suferit un AVC. Acest lucru arată faptul că există o legătură directă între nivelul mediu de glucoză din sânge și posibilitatea mai mare de a avea un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(<span class="at">x =</span> avg_glucose_level, <span class="at">fill =</span> stroke)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Stroke"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Densitate age – stroke</strong></p>
<p>Graficul relației dintre vârstă și apariția unui AVC arată faptul că pacienții cu o vârstă de cel puțin 50 de ani au suferit un AVC (în special intervalul de [70, 80] ani), în timp ce pacienții cu vârste mai mici de 20 de ani nu au suferit un AVC. Acest lucru arată faptul că există o legătură directă între vârstă și posibilitatea mai mare de a avea un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">fill =</span> stroke)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Stroke"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Densitate bmi – stroke</strong></p>
<p>Graficul relației dintre indicele de masă corporală și apariția unui AVC arată faptul că pacienții cu o valoare a indicelui cuprinsă între 25 și 40 kg/m² au suferit un AVC. De asemenea, pacienții care înregistrează o valoare a indicelui mai mică de 25 kg/m² nu au suferit un AVC. Acest lucru arată faptul că există o legătură directă între indicele de masă corporală și posibilitatea mai mare de a avea un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">fill =</span> stroke)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Stroke"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Distrbuția variabilelor categoriale</strong></p>
<ul>
<li>Stroke: observăm distribuția persoanelor care au suferit un AVC (4700) și a celor care nu au suferit un AVC (201)</li>
<li>Gender: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor de gen feminin</li>
<li>Hypertension: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care nu suferă de hipertensiune</li>
<li>heart_disease: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care nu suferă de boli de inimă</li>
<li>ever_married: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care sunt căsătorite</li>
<li>work_type: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care lucrează în domeniul privat</li>
<li>residence_type: observăm distribuția aproximativ egală a pacienților care au suferit un AVC în rândul persoanelor care provin atât din mediul urban, cât și din mediul rural</li>
<li>smoking_status: observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care nu au fumat niciodată</li>
</ul>
<div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gender, hypertension, heart_disease, ever_married, work_type, Residence_type, smoking_status, stroke</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>var_stroke <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Stroke variable"</span>, <span class="at">x =</span> <span class="st">"Stroke"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>var_stroke</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>var_gender <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(gender, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Gender variable"</span>, <span class="at">x =</span> <span class="st">"Stroke"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>var_gender</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>var_hypertension <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(hypertension, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Hypertension variable"</span>, <span class="at">x =</span> <span class="st">"Hypertension"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>var_hypertension</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>var_heart_disease <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(heart_disease, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Heart_disease variable"</span>, <span class="at">x =</span> <span class="st">"Heart_disease"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>var_heart_disease</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>var_ever_married <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(ever_married, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Ever_married variable"</span>, <span class="at">x =</span> <span class="st">"Ever_married"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>var_ever_married</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>var_work_type <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(work_type, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Work_type variable"</span>, <span class="at">x =</span> <span class="st">"Work_type"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>var_work_type</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>var_Residence_type <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(Residence_type, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Residence_type variable"</span>, <span class="at">x =</span> <span class="st">"Residence_type"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>var_Residence_type</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>var_smoking_status <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data2, <span class="fu">aes</span>(smoking_status, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Smoking_status variable"</span>, <span class="at">x =</span> <span class="st">"Smoking_status"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>var_smoking_status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-6.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-12-8.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>De asemenea, am transformat variabila numerică bmi într-o variabilă calitativă pentru a putea evidenția mai clar legătura dintre masa corporală și posibilitatea de a manifesta un AVC. Astfel, pentru o valoare a indicelui de masă corporală &lt; 18.5, pacientul este considerat subponderal, pentru intervalul [18.5, 25], pacientul este considerat cu o greutate normală, pentru intervalul [25, 30], pacientul este considerat supraponderal, iar pentru o valoare &gt; 30, pacientul este considerat obez. Astfel, observăm predominanța pacienților care au suferit un AVC în rândul persoanelor care sunt supraponderale sau obeze.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>stroke_data3 <span class="ot">&lt;-</span> stroke_pred <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hypertension =</span> <span class="fu">if_else</span>(hypertension <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">heart_disease =</span> <span class="fu">if_else</span>(heart_disease <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi=</span> <span class="fu">case_when</span>(bmi <span class="sc">&lt;</span> <span class="fl">18.5</span> <span class="sc">~</span> <span class="st">"Underweight"</span>, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                        bmi <span class="sc">&gt;=</span> <span class="fl">18.5</span> <span class="sc">&amp;</span> bmi <span class="sc">&lt;</span> <span class="dv">25</span> <span class="sc">~</span> <span class="st">"Healthy"</span>, </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                        bmi <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> bmi <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">'Overweight'</span> , </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                        bmi <span class="sc">&gt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"Obesity"</span>),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">stroke =</span> <span class="fu">if_else</span>(stroke <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="sc">%&gt;%</span> </span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id gender age hypertension heart_disease ever_married     work_type
1  9046   Male  67           No           Yes          Yes       Private
2 51676 Female  61           No            No          Yes Self-employed
3 31112   Male  80           No           Yes          Yes       Private
4 60182 Female  49           No            No          Yes       Private
5  1665 Female  79          Yes            No          Yes Self-employed
6 56669   Male  81           No            No          Yes       Private
  Residence_type avg_glucose_level        bmi  smoking_status stroke
1          Urban            228.69    Obesity formerly smoked    Yes
2          Rural            202.21    Obesity    never smoked    Yes
3          Rural            105.92    Obesity    never smoked    Yes
4          Urban            171.23    Obesity          smokes    Yes
5          Rural            174.12    Healthy    never smoked    Yes
6          Urban            186.21 Overweight formerly smoked    Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>var_bmi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(stroke_data3, <span class="fu">aes</span>(bmi, <span class="at">fill =</span> stroke))<span class="sc">+</span><span class="fu">geom_bar</span>()<span class="sc">+</span><span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"grey97"</span>))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar graph of Bmi variable"</span>, <span class="at">x =</span> <span class="st">"Bmi"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>var_bmi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Matricea de corelație</strong></p>
<p>Pentru confirmarea rezultatelor de mai sus, am ales să realizăm matricea de corelație a variabilelor de tip numeric din setul de date inițial. Astfel, observăm prezența corelațiilor pozitive între atribute. Referitor la variabila de referință ”Stroke”, se remarcă faptul că apariția unui AVC este cel mai mult influențată de vârsta pacientului (0.23), în raport cu variabilele reprezentate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("corrplot")</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>col_corr <span class="ot">&lt;-</span> stroke_pred <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">'age'</span>, <span class="st">'hypertension'</span>, <span class="st">'heart_disease'</span>, <span class="st">'avg_glucose_level'</span>, <span class="st">'stroke'</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>col_bmi <span class="ot">&lt;-</span> stroke_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">'bmi'</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>data_corr <span class="ot">&lt;-</span> <span class="fu">cbind</span>(col_corr, col_bmi)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>data_Corr2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data_corr)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co">#data_Corr2</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>data_corr_std<span class="ot">&lt;-</span><span class="fu">scale</span>(data_Corr2)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co">#data_corr_std</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(data_corr_std), <span class="at">method=</span><span class="st">"number"</span>, <span class="at">type=</span><span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Recodificare date</strong></p>
<p>Pentru a putea aplica regresia logistică și arborii de clasificare am transformat variabilele calitative din setul inițial în variabile numerice. De asemenea, am împărțit setul de date în două subseturi, setul de antrenare - care conține 75% din numărul total de observații (3682) și setul de testare - care conține restul de 25% din observații (1227).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># head(stroke_pred)</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>stroke_data4 <span class="ot">&lt;-</span> stroke_pred <span class="sc">%&gt;%</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">if_else</span>(gender<span class="sc">==</span><span class="st">"Female"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ever_married =</span> <span class="fu">if_else</span>(ever_married <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">work_type =</span> <span class="fu">case_when</span>(work_type <span class="sc">==</span> <span class="st">"children"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>                               work_type <span class="sc">==</span> <span class="st">"Govt_job"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>                               work_type <span class="sc">==</span> <span class="st">"Never_worked"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>                               work_type <span class="sc">==</span> <span class="st">"Self-employed"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>                               work_type <span class="sc">==</span> <span class="st">"Private"</span> <span class="sc">~</span> <span class="dv">4</span>),</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Residence_type =</span> <span class="fu">if_else</span>(Residence_type <span class="sc">==</span> <span class="st">"Urban"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">bmi=</span> <span class="fu">as.double</span>(bmi),</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">smoking_status =</span> <span class="fu">case_when</span>(smoking_status <span class="sc">==</span> <span class="st">"never smoked"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>                                    smoking_status <span class="sc">==</span> <span class="st">"formerly smoked"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>                                    smoking_status <span class="sc">==</span> <span class="st">"smokes"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>                                    smoking_status <span class="sc">==</span> <span class="st">"Unknown"</span> <span class="sc">~</span> <span class="dv">3</span>),</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">stroke =</span> <span class="fu">if_else</span>(stroke <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="sc">%&gt;%</span> </span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mask$eval_all_mutate(quo): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_data4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id gender age hypertension heart_disease ever_married work_type
1  9046      0  67            0             1            1         4
2 51676      1  61            0             0            1         3
3 31112      0  80            0             1            1         4
4 60182      1  49            0             0            1         4
5  1665      1  79            1             0            1         3
6 56669      0  81            0             0            1         4
  Residence_type avg_glucose_level  bmi smoking_status stroke
1              1            228.69 36.6              1    Yes
2              0            202.21   NA              0    Yes
3              0            105.92 32.5              0    Yes
4              1            171.23 34.4              2    Yes
5              0            174.12 24.0              0    Yes
6              1            186.21 29.0              1    Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>stroke_data5 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(stroke_data4)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_data5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id gender age hypertension heart_disease ever_married work_type
1  9046      0  67            0             1            1         4
3 31112      0  80            0             1            1         4
4 60182      1  49            0             0            1         4
5  1665      1  79            1             0            1         3
6 56669      0  81            0             0            1         4
7 53882      0  74            1             1            1         4
  Residence_type avg_glucose_level  bmi smoking_status stroke
1              1            228.69 36.6              1    Yes
3              0            105.92 32.5              0    Yes
4              1            171.23 34.4              2    Yes
5              0            174.12 24.0              0    Yes
6              1            186.21 29.0              1    Yes
7              0             70.09 27.4              0    Yes</code></pre>
</div>
</div>
</section>
<section id="regresie-logistică" class="level2">
<h2 class="anchored" data-anchor-id="regresie-logistică">Regresie Logistică</h2>
<p>Pentru a construi modelul de regresie, vom utiliza funcția “glm ()” - General Linear Model.</p>
<p>Observăm cum pentru variabilele age, hypertension, heart_disease și avg_glucose_level valorile p-value sunt sub pragul de 0.05, ceea ce înseamnă că doar acestea sunt reprezentative pentru modelul nostru, având o influență asupra posibilității de a suferi sau nu un AVC.</p>
<p>Totuși, putem determina discrepanțele dintre modelul curent, cel care conține un coeficient pentru fiecare variabilă independentă și modelul nul, cel care conține doar termenul liber. Devianța nulă (Null deviance) sau reziduală (Residual deviance) reprezintă suma pătratelor abaterilor din modelele de regresie estimate cu metoda celor mai mici pătrate. Devianța nulă ilustrează cât de bun este răspunsul prognozat de un model în care apare numai termenul liber, în timp ce Devianța reziduală (a modelului) arată cât de bun este răspunsul prognozat de un model în care se adaugă variabilele independente.</p>
<p>Cu cât valoarea deviației este mai mică, cu atât modelul este mai bun din punct de vedere statistic. Tocmai de aceea, datorită faptului că deviația reziduală are o valoare de 1037.5 &lt; 1297.9, valoarea deviației nule, putem afirma faptul că modelul curent este mai adecvat decât modelul nul.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("caTools")</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extrage 2 esantioane (75% din obs vs 25% din obs)</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>split<span class="ot">=</span><span class="fu">sample.split</span>(stroke_data5<span class="sc">$</span>stroke, <span class="at">SplitRatio=</span><span class="fl">0.75</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="co">#split</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Subm pt care split = TRUE</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>setantrenare<span class="ot">&lt;-</span><span class="fu">subset</span>(stroke_data5, split<span class="sc">==</span><span class="cn">TRUE</span>)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="co">#setantrenare</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3682 obs</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>settestare<span class="ot">&lt;-</span><span class="fu">subset</span>(stroke_data5, split<span class="sc">==</span><span class="cn">FALSE</span>)</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="co"># settestare </span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 1227 obs</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Model regresie</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">glm</span>(stroke<span class="sc">~</span>gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span>heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>setantrenare, <span class="at">family =</span> binomial)</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = stroke ~ gender + age + hypertension + heart_disease + 
    ever_married + work_type + Residence_type + avg_glucose_level + 
    bmi + smoking_status, family = binomial, data = setantrenare)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.1738  -0.2964  -0.1638  -0.0835   3.6071  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -7.973851   0.698661 -11.413  &lt; 2e-16 ***
gender             0.091838   0.177241   0.518   0.6044    
age                0.061641   0.006491   9.496  &lt; 2e-16 ***
hypertension       0.521101   0.204087   2.553   0.0107 *  
heart_disease      0.516949   0.235778   2.193   0.0283 *  
ever_married       0.077446   0.287831   0.269   0.7879    
work_type          0.047687   0.086189   0.553   0.5801    
Residence_type     0.090534   0.172715   0.524   0.6002    
avg_glucose_level  0.006124   0.001491   4.109 3.98e-05 ***
bmi                0.006653   0.013052   0.510   0.6103    
smoking_status    -0.015103   0.077702  -0.194   0.8459    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1297.9  on 3681  degrees of freedom
Residual deviance: 1037.5  on 3671  degrees of freedom
AIC: 1059.5

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>Vom cerceta impactul variabilelor analizate asupra șanselor unui pacient de a suferi sau nu un AVC prin aplicarea funcției exponențiale asupra coeficienților modelului de regresie logistică. Spre exemplu, interpretând câteva rezultate, obținem:</p>
<ul>
<li><p>atunci când vârsta crește cu o unitate, șansele de manifestare a unui AVC cresc cu 6.35%</p></li>
<li><p>atunci când indicele masei corporale crește cu o unitate, șansele de manifestare a unui AVC cresc cu 0.66%</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Functia exponentiala</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)            gender               age      hypertension 
     0.0003443503      1.0961869017      1.0635800060      1.6838812056 
    heart_disease      ever_married         work_type    Residence_type 
     1.6769030598      1.0805241684      1.0488424835      1.0947587977 
avg_glucose_level               bmi    smoking_status 
     1.0061432783      1.0066749422      0.9850105016 </code></pre>
</div>
</div>
<p><strong>Predicție</strong></p>
<p>Pe baza modelului, am previzionat șansele ca un pacient să fie predispus la apariția unui AVC, utilizând setul de testare.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictie</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pred<span class="ot">=</span> <span class="fu">predict</span>(model, settestare, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          5          8         21         27         29 
0.20763215 0.26023711 0.06800430 0.11166953 0.05645367 0.17669380 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pred2<span class="ot">=</span><span class="fu">ifelse</span>(pred<span class="sc">&gt;</span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1  5  8 21 27 29 
 0  0  0  0  0  0 </code></pre>
</div>
</div>
<p><strong>Matrice de confuzie</strong></p>
<p>Pe liniile matricei de confuzie se află etichetele previzionate, iar pe coloane, etichetele reale din setul de testare. Astfel, setul de antrenare conține 0 + 1 = 1 pacient care este predispus la apariția unui AVC și 1175+51 = 1226 pacienți care nu sunt predispuși la apariția unui AVC.</p>
<p>Pacientul predispus la apariția unui AVC a fost corect clasificat, în timp ce din cei 1226 de pacienți care nu sunt predispuși la apariția unui AVC, 1175 au fost clasificați corect ca nefiind predispuși la acest risc, în timp ce 51 au fost eronat clasificați.</p>
<p>Acuratețea clasificării se determină ca raportul dintre suma elementelor de pe diagonala principală și suma tuturor elementelor din această matrice. Astfel, rata de acuratețe este de (1175+1) / (1175+1+0+51) = 1176 / 1227 = 0.9584 (95.64%). Acest rezultat arată faptul că 95.64% din elementele setului de testare au fost corect previzionate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matricea de confuzie</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>conf_matrix<span class="ot">&lt;-</span><span class="fu">table</span>(settestare<span class="sc">$</span>stroke, pred2)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>conf_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pred2
         0    1
  No  1175    0
  Yes   51    1</code></pre>
</div>
</div>
<p><strong>Curba ROC</strong></p>
<p>Un alt instrument utilizat pentru acuratețea modelului este Curba ROC. O evaluare a clasificării este dată de apartenenţa indicatorului AUC (aria de sub curba ROC) la subintervale ale lui [0.5,1]. Întrucât valoarea de 0.86 aparține intervalului [0.8, 0.9] =&gt; această clasificare este evaluată ca fiind una bună, existând 86% șanse ca modelul să poată distinge între clasa pozitivă (pacienții predispuși la AVC) și clasa negativă (pacienții care nu sunt predispuși la AVC).</p>
<p>Astfel, putem afirma că modelul de regresie este o metodă reprezentativă pentru setul de date analizat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Curba ROC - Instrument pentru acuratete</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ROCR")</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>p<span class="ot">&lt;-</span><span class="fu">predict</span>(model, <span class="at">newdata=</span>settestare, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co"># rata TP</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>pr<span class="ot">&lt;-</span><span class="fu">prediction</span>(p, settestare<span class="sc">$</span>stroke)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="co"># rata FP</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>prf<span class="ot">&lt;-</span><span class="fu">performance</span>(pr, <span class="at">measure=</span><span class="st">"tpr"</span>, <span class="at">x.measure=</span><span class="st">"fpr"</span>)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aria de sub curba ROC</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>auc<span class="ot">&lt;-</span><span class="fu">performance</span>(pr, <span class="at">measure=</span><span class="st">"auc"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>auc<span class="ot">&lt;-</span>auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]]</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>auc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.858838</code></pre>
</div>
</div>
</section>
<section id="arbori-de-clasificare" class="level2">
<h2 class="anchored" data-anchor-id="arbori-de-clasificare">Arbori de Clasificare</h2>
<p>Clasificarea oferă modelul predictiv sau funcția care prezice noile date în categorii sau etichete distincte pe baza datelor istorice, fiind evaluată prin acuratețea clasificării. Astfel, folosind arborii de clasificare ne-am propus să avem în vedere variabila stroke (binară) care prin valorile de Yes și No arată dacă un pacient din setul de date este predispus la apariția unui AVC.</p>
<p>De menționat este faptul că am păstrat aceeași modalitate de împărțire a setului de date: 3682 de observații pentru setul de antrenare și 1227 de observații pentru setul de testare.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Extrage 2 esantioane (75% din obs vs 25% din obs)</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>split2<span class="ot">=</span><span class="fu">sample.split</span>(stroke_data5<span class="sc">$</span>stroke, <span class="at">SplitRatio=</span><span class="fl">0.75</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="co"># split2</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Subm pt care split = TRUE</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>setantrenare2<span class="ot">&lt;-</span><span class="fu">subset</span>(stroke_data5, split2<span class="sc">==</span><span class="cn">TRUE</span>)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co"># setantrenare2</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3682 obs</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>settestare2<span class="ot">&lt;-</span><span class="fu">subset</span>(stroke_data5, split2<span class="sc">==</span><span class="cn">FALSE</span>)</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="co"># settestare </span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 1227 obs</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke_data5,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id gender age hypertension heart_disease ever_married work_type
1   9046      0  67            0             1            1         4
3  31112      0  80            0             1            1         4
4  60182      1  49            0             0            1         4
5   1665      1  79            1             0            1         3
6  56669      0  81            0             0            1         4
7  53882      0  74            1             1            1         4
8  10434      1  69            0             0            0         4
10 60491      1  78            0             0            1         4
11 12109      1  81            1             0            1         4
12 12095      1  61            0             1            1         1
   Residence_type avg_glucose_level  bmi smoking_status stroke
1               1            228.69 36.6              1    Yes
3               0            105.92 32.5              0    Yes
4               1            171.23 34.4              2    Yes
5               0            174.12 24.0              0    Yes
6               1            186.21 29.0              1    Yes
7               0             70.09 27.4              0    Yes
8               1             94.39 22.8              0    Yes
10              1             58.57 24.2              3    Yes
11              0             80.43 29.7              0    Yes
12              0            120.46 36.8              2    Yes</code></pre>
</div>
</div>
<p>Pentru construirea arborelui de clasificare am utilizat funcția tree (). Astfel, arborele conține 4 noduri terminale. Observăm atât faptul că variabila de la rădăcina arborelui și anume age este cea care are cea mai mare putere de clasificare în realizarea arborelui, cât și faptul că eticheta “No” este predominantă (cea mai mare probabilitate pe fiecare nivel al arborelui), având în vedere datele analizate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tree")</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tree)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>arbore <span class="ot">&lt;-</span> <span class="fu">tree</span>(setantrenare2<span class="sc">$</span>stroke<span class="sc">~</span>gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span>heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>setantrenare2)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co"># head(setantrenare2,10)</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(arbore)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(arbore, <span class="at">pretty=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Script_ȚancuMihaelaIsabelle_ȚușcăAndreea_VulturescuDusyTheodora_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Astfel, pentru o vârstă mai mică de 47.5 ani, șansele ca un pacient să nu fie predispus la apariția unui AVC sunt în proporție de 99%. Totodată observăm cum ramificarea în funcție de nivelul mediu de glucoză din sânge ne sugerează faptul că pentru un nivel mai mic de 183.7 mmol/l, șansele ca un pacient să sufere un AVC sunt în proporție de 11.03%, în timp ce pentru o valoare mai mare de acest prag, chiar dacă observăm că eticheta predominantă rămâne “No”, șansele ca un pacient să sufere un AVC înregistrează o ușoară creștere, atingând valoarea de 26.49%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arbore)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>node), split, n, deviance, yval, (yprob)
      * denotes terminal node

 1) root 3682 1298.0 No ( 0.957360 0.042640 )  
   2) age &lt; 47.5 2028  115.5 No ( 0.995562 0.004438 ) *
   3) age &gt; 47.5 1654  996.8 No ( 0.910520 0.089480 )  
     6) age &lt; 67.5 1058  449.6 No ( 0.945180 0.054820 ) *
     7) age &gt; 67.5 596  505.9 No ( 0.848993 0.151007 )  
      14) avg_glucose_level &lt; 183.87 445  312.8 No ( 0.887640 0.112360 ) *
      15) avg_glucose_level &gt; 183.87 151  174.6 No ( 0.735099 0.264901 ) *</code></pre>
</div>
</div>
<p><strong>Predicție</strong></p>
<p>În continuare, am realizat predicția pe setul de testare, de unde putem observa cum pacienții considerați nu prezintă riscul de a suferi un AVC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predictie </span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>pred_ar <span class="ot">&lt;-</span> <span class="fu">predict</span>(arbore, settestare2, <span class="at">type=</span><span class="st">'class'</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># pred_ar</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred_ar,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] No No No No No No No No No No
Levels: No Yes</code></pre>
</div>
</div>
<p><strong>Matricea de confuzie</strong></p>
<p>Totuși, matricea de confuzie arată faptul că 52 dintre pacienții care sunt predispuși la apariția unui AVC au fost incorect clasificați prin intermediul acestui model. În același timp, eroarea de clasificare arată faptul că 4.24% din observațiile setului de testare au fost previzionate incorect, iar restul de 95.76% au fost previzionate corect.</p>
<p>Având în vedere rezultatele obținute, putem afirma că și arborii de clasificare pot fi considerați drept o metodă reprezentativă pentru predicția unui AVC pe baza datelor istorice din setul de date, însă ar fi necesară existența unui număr mai mare de observații.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matr de confuzie</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>confuzie<span class="ot">&lt;-</span><span class="fu">table</span>(pred_ar,settestare2<span class="sc">$</span>stroke)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>confuzie</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
pred_ar   No  Yes
    No  1175   52
    Yes    0    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(pred_ar<span class="sc">!=</span>settestare2<span class="sc">$</span>stroke),<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.24</code></pre>
</div>
</div>
</section>
<section id="concluzii" class="level2">
<h2 class="anchored" data-anchor-id="concluzii">Concluzii</h2>
<p>Așadar, proiectul curent a avut ca și scop predicția apariției unui accident vascular cerebral, având în vedere diverși factori de risc, pe baza unor date disponibile cu privire la un eșantion de pacienți.</p>
<p>Pentru a realiza analiza, am aplicat inițial asupra setului de date diverse tehnici pentru a curăța și înțelege componența și semnificația variabilelor considerate. Astfel, am putut observa distribuția atât a variabilelor discrete, cât și a variabilelor calitative, am analizat densitățile atributelor numerice în raport cu apariția unui AVC.</p>
<p>Am continuat prin aplicarea unui model de regresie și a arborilor de clasificare pentru a putea realiza o predicție pe baza acestora, fiind necesară împărțirea setului inițial în două seturi de date (de antrenare, respectiv de testare). Tehnicile ne-au arătat cum variabilele legate de vârstă, alte boli de care pacientul suferă și nivelul mediu de glucoză din sânge sunt cele care influențează cel mai mult șansele de apariție ale unui AVC. Referitor la acuratețea previziunilor, regresia logistică a arătat faptul că 95.64% din observațiile setului de testare au fost corect previzionate, în timp ce pentru arborii de clasificare s-a înregistrat o eroare de clasificare de 4.24%, ceea ce înseamnă că 95.76% din elementele setului de testare au fost corect previzionate.</p>
<p>Chiar dacă rezultatele arată că ambele metode pot fi considerate reprezentative pentru predicția unui AVC, totuși, au existat câteva limitări cu privire la dimensiunea eșantionului ales, dar și la faptul că doar în proporție de 4% pacienții din setul de date au suferit un AVC. De asemenea, pentru o previziune cu o acuratețe mai mare, ar trebui incluși în analiză și alți factori (genetici sau care fac referire la stilul de viață) ce pot influența concluziile unei astfel de analize.</p>
<p>Referitor la îmbunătățiri, pe lângă sporirea complexității setului de date, se regăsește necesitatea continuării cercetărilor în domeniu, pentru reducerea riscului unui pacient de a suferi un AVC, prin aplicarea unor metode și tehnici de machine learning sau data mining.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>